---
title: "Drifter Data - CSV to KML"
author: "Kourtney Burger"
date: "2025-01-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)

# Load packages
library(tidyverse)
library(xml2)
library(here)
```

# Read in data

```{r}
#data <- read.csv("GPS data/CalCurCEAS_027_GPS.csv")

csv_files <- list.files(path = here('data/GPS/DASBRs'), pattern = "\\.csv$", full.names = TRUE)
```

# Create a KML document

```{r}
# Function to create KML from multiple CSV files using xml2
create_kml_from_csv <- function(csv_files, kml_output) {
  
  # Create an empty KML structure using xml2
  kml_data <- xml_new_root("kml", xmlns = "http://www.opengis.net/kml/2.2")
  document_node <- xml_add_child(kml_data, "Document")
  
  # Loop through each CSV file
  for (csv_file in csv_files) {
    
    # Read the CSV file
    data <- read.csv(csv_file)
    
    # Check for required columns
    if (!all(c("Latitude", "Longitude", "UTC") %in% colnames(data))) {
      stop(paste("CSV file", csv_file, "does not have the required columns"))
    }
    
    # Loop through each row of the CSV data
    for (i in 1:nrow(data)) {
      
      # Create a placemark for each row in the CSV
      placemark <- xml_add_child(document_node, "Placemark")
      
      # Add the name (can be based on the timestamp or other fields)
      xml_add_child(placemark, "name", paste("Point at", data$UTC[i]))
      
      # Add timestamp (convert to TimeStamp tag)
      time_node <- xml_add_child(placemark, "TimeStamp")
      xml_add_child(time_node, "when", data$UTC[i])
      
      # Add the Point and coordinates
      point_node <- xml_add_child(placemark, "Point")
      coords <- paste(data$Longitude[i], data$Latitude[i], "0", sep = ",")
      xml_add_child(point_node, "coordinates", coords)
    }
  }
  
  # Save the KML to the specified output file
  write_xml(kml_data, kml_output)
  cat("KML file created:", kml_output, "\n")
}
```

# Test with all CalCurCEAS data

-   note, this crashed Google Earth

```{r}
# Define the path to the "GPS data" folder
folder_path <- "GPS data"

# Get the list of CSV files in the folder
csv_files <- list.files(path = folder_path, pattern = "\\.csv$", full.names = TRUE)

# Check the CSV files in the folder
print(csv_files)

# Define the output KML file
kml_output <- here('output/DASBRs.kml')

# Create KML from the CSV files in the "GPS data" folder
create_kml_from_csv(csv_files, kml_output)
```

# Test with Oregon Subset

```{r}
# Define the path to the "GPS data" folder
folder_path <- "GPS data/Oregon Subset/"

# Get the list of CSV files in the folder
csv_files <- list.files(path = folder_path, pattern = "\\.csv$", full.names = TRUE)

# Check the CSV files in the folder
print(csv_files)

# Define the output KML file
kml_output <- here('output/OregonDASBRs.kml')

# Create KML from the CSV files in the "GPS data" folder
create_kml_from_csv(csv_files, kml_output)
```
